import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  viewTitulo: {
    flex: 3,
    justifyContent: "center",
  },
  tituloCadastro: {
    paddingLeft: "5%",
    marginBottom: "5%",
    fontFamily: "Montserrat_800ExtraBold",
    fontStyle: "normal",
    fontWeight: "800",
    fontSize: 36,
    lineHeight: 40,
    textAlign: "left",
    color: "#000000",
  },
  tituloTexto: {
    fontFamily: "Montserrat_500Medium",
    fontStyle: "normal",
    fontWeight: "500",
    fontSize: 17,
    lineHeight: 24,
    color: "#474A57",
    paddingLeft: "5%",
  },
  viewFormulario: {
    flex: 6,
    paddingHorizontal: "8%",
  },
  inputNomeCompleto: {
    marginVertical: "4%",
    paddingHorizontal: 20,
    paddingVertical: "3%",
    borderWidth: 2,
    borderRadius: 16,
    borderColor: "#18191F",
    borderStyle: "solid",
    fontFamily: "Montserrat_500Medium",
    fontSize: 21,
    fontStyle: "normal",
    color: "#474A57",
  },
  inputEmail: {
    marginVertical: "4%",
    paddingHorizontal: 20,
    paddingVertical: "3%",
    borderWidth: 2,
    borderRadius: 16,
    borderColor: "#18191F",
    borderStyle: "solid",
    fontFamily: "Montserrat_500Medium",
    fontSize: 21,
    fontStyle: "normal",
    color: "#474A57",
  },
  inputSenha: {
    marginVertical: "4%",
    paddingHorizontal: 20,
    paddingVertical: "3%",
    borderWidth: 2,
    borderRadius: 16,
    borderColor: "#18191F",
    borderStyle: "solid",
    fontFamily: "Montserrat_500Medium",
    fontSize: 21,
    fontStyle: "normal",
    color: "#474A57",
  },
  textoEscolhaPerfil: {
    fontFamily: "Montserrat_500Medium",
    fontStyle: "normal",
    fontSize: 17,
    lineHeight: 24,
    color: "#474A57",
  },
  botaoCadastro: {
    marginVertical: "15%",
    paddingHorizontal: "4%",
    paddingVertical: "3%",
    borderWidth: 2,
    borderRadius: 16,
    borderColor: "#18191F",
    borderStyle: "solid",
    backgroundColor: "#69D669",
    alignItems: "center",
  },
  botaoCadastroText: {
    fontFamily: "Montserrat_800ExtraBold",
    fontStyle: "normal",
    fontWeight: "800",
    fontSize: 21,
    color: "white",
  },
  viewLogin: {
    flex: 1,
  },
  textLogin: {
    fontFamily: "Montserrat_500Medium",
    fontStyle: "normal",
    fontWeight: "500",
    fontSize: 13,
    textAlign: "center",
  },
  linkLogin: {
    fontFamily: "Montserrat_800ExtraBold",
    fontStyle: "normal",
    fontWeight: "800",
    fontSize: 13,
    color: "#F95A2C",
  },
});
